# note, the nuget org token expires around June 2021

name: Build/test/docs/publish

on:
  push:
    branches:
      - dev
    tags:        
      - v*             # Push events to v1.2.3 tag
  workflow_dispatch:

jobs:
 
  pack_cpu:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install agent
      uses: step-security/test@main
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --configuration Release --verbosity normal
